### ISSUE TITLE
HTML only version?

### ISSUE THREAD

**Issue by kokujin** [DavidJoyceIre/Zurb-Foundation-Ecommerce-Template#1]
Hi! Would this template be offered as a HTML only template in the near future? Do you have screenshots?

**Comment by DavidJoyceIre** [comment]
Hi Kokujin

https://github.com/DavidJoyceIre/JewellerStoreEcommerceTemplate is a HTML only version this. The only difference been that there isn't a back end dashboard

**Comment by kokujin** [comment]
Thanks for the link @DavidJoyceIre. I wonder why this project has only garnered 4 stars? Keep up with the great work.
