### ISSUE TITLE
Contributors?

### ISSUE THREAD

**Issue by kokujin** [DavidJoyceIre/Zurb-Foundation-Ecommerce-Template#2]
Are you open to contributors for this project?

**Comment by DavidJoyceIre** [comment]
Hi Kokujin

Yes that would be great

...

*David Joyce, Full Stack Software and Web Developer*
*tel:         *+353 (0) 87 9980396
*skype:   *mrdavejoyce
*web:      *JoyceSoftware.com <http://www.joycesoftware.com>

*social media*
Follow me on Twitter <http://twitter.com/DaveJoyceIE>
Connect with me on LinkedIn
<http://www.linkedin.com/pub/dave-joyce/48/833/53b>

*other*
HTML E-Commerce Template (Free)
<https://github.com/DavidJoyceIre/Zurb-Foundation-Ecommerce-Template>
HTML Dashboard Template (Free)
<https://github.com/DavidJoyceIre/HTML-Dashboard>

**Comment by kokujin** [comment]
Ooops, I actually meant as a contributor to the Foundation/ HTML template project

**Comment by DavidJoyceIre** [comment]
Hi Kokujin

No problem on that one too :)

...

*David Joyce, Full Stack Software and Web Developer*
*tel:         *+353 (0) 87 9980396
*skype:   *mrdavejoyce
*web:      *JoyceSoftware.com <http://www.joycesoftware.com>

*social media*
Follow me on Twitter <http://twitter.com/DaveJoyceIE>
Connect with me on LinkedIn
<http://www.linkedin.com/pub/dave-joyce/48/833/53b>

*other*
HTML E-Commerce Template (Free)
<https://github.com/DavidJoyceIre/Zurb-Foundation-Ecommerce-Template>
HTML Dashboard Template (Free)
<https://github.com/DavidJoyceIre/HTML-Dashboard>
